### ISSUE TITLE
fix: Geo类型的热力图的文档参数缺失

### ISSUE THREAD

**Issue by ChenJiaH** [ecomfe/echarts-www#1]
背景：
使用heatmap时，想调整默认点大小，查文档未发现配置项后，查源码发现可通过 pointSize 配置，默认值20

文档链接：
https://echarts.apache.org/en/option.html#series-heatmap.type

缺少参数：

| 参数名 | 参数类型 | 默认值 |
| :-:  | :-: | :-: |
| pointSize | Number | 20 |

**Comment by Ovilia** [comment]
Thanks for reporting.
I've opened an issue [here](https://github.com/apache/incubator-echarts-doc/issues/63). You may also provide a pull request to that repo if you wish to contribute.
